name: Tests
on:
  push:
  pull_request:
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm clean-install
      # TODO: actually write and run tests
      - run: npm run prepublishOnly
